sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build image
- docker build -t alexadhy/rpi-alpine:build .
# test image
- docker run alexadhy/rpi-alpine:build uname -a
# push image
-  TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
-  docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
-  docker tag alexadhy/rpi-alpine:build alexadhy/rpi-alpine:$TAG
-  docker push alexadhy/rpi-alpine:$TAG
